# YOLOv5 🚀 by Ultralytics, GPL-3.0 license
# Builds ultralytics/yolov5:latest images on DockerHub https://hub.docker.com/r/ultralytics/yolov5

name: Publish Docker Images

on:
  push:
    branches: [master]

jobs:
  docker:
    if: github.repository == 'VisioLab/yolov5'
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Configure docker auth
        shell: bash
        run: |
          gcloud auth configure-docker europe-docker.pkg.dev -q

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push GPU image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: utils/docker/Dockerfile
          push: true
          tags: europe-docker.pkg.dev/visiolab-shared-4d71/images/yolov5:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MACHINEUSER_PAT}}
