# YOLOv5 🚀 by Ultralytics, GPL-3.0 license
# Builds ultralytics/yolov5:latest images on DockerHub https://hub.docker.com/r/ultralytics/yolov5

name: Publish Docker Images

on:
  push:
    branches: [master]
  pull_request:

jobs:
  docker:
    if: github.repository == 'VisioLab/yolov5' && (github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'push-image'))
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
      issues: "write"
      pull-requests: "write"
      checks: "write"
      statuses: "write"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Configure docker auth
        shell: bash
        run: |
          gcloud auth configure-docker europe-docker.pkg.dev -q

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-name@v6
      - name: Set tag if push to master
        if: github.event_name == 'push'
        run: |
          echo "image_tag=latest" >> $GITHUB_ENV
      - name: Set tag if PR
        if: github.event_name == 'pull_request'
        run: |
          echo "image_tag=${{ steps.branch-name.outputs.current_branch }}" >> $GITHUB_ENV
      - name: Build and push GPU image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: utils/docker/Dockerfile
          push: true
          tags: europe-docker.pkg.dev/${{ secrets.ARTIFACT_REPOSITORY_ID }}/yolov5:${{ env.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MACHINEUSER_PAT}}
